version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DB_HOST=timescale
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=medicaldb
    ports:
      - "8000:8000"
    networks:
      - app-network
  data_generator:
    build:
      context: .
      dockerfile: Dockerfile.data_generator
    environment:
      - DB_HOST=timescale
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=medicaldb
      - API_URL=http://api:8000/write
    networks:
      - app-network
networks:
  app-network: