version: '3.8'
services:
  timescale:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_DB=medicaldb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DB_HOST=timescale
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=medicaldb
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - timescale
  data_generator:
    build:
      context: .
      dockerfile: Dockerfile.data_generator
    environment:
      - DB_HOST=timescale
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=medicaldb
      - API_URL=http://api:8000/write
    networks:
      - app-network
    depends_on:
      - api
      - timescale 
networks:
  app-network: